# Generated by Django 3.1 on 2021-10-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('hairColor', 'Hair Color'), ('capSize', 'Cap Size')], max_length=100),
        ),
    ]
